### ISSUE TITLE
gap_fit command line issue on Mac

### ISSUE THREAD

**Issue by bernstei** [libAtoms/quippy-wheels#1]
I just tried to install from the pypi test server i.e. `pip install -i https://test.pypi.org/simple/ quippy-ase`, and when I try to run `gap_fit`, just to see if it chokes on libraries or something, I get the following, which looks like maybe the wrapping or argv is broken.

```
bernstei@Noams-MacBook-Pro ~ % gap_fit -help 
libAtoms::Hello World: 02/06/2021   13:51:16
libAtoms::Hello World: git version  https://github.com/libAtoms/QUIP,cd51461f0-dirty
libAtoms::Hello World: QUIP_ARCH    darwin_x86_64_gfortran_openmp
libAtoms::Hello World: compiled on  Jun  1 2021 at 19:53:04
libAtoms::Hello World: OpenMP parallelisation with 4 threads
WARNING: libAtoms::Hello World: environment variable OMP_STACKSIZE not set explicitly. The default value - system and compiler dependent - may be too small for some applications.
libAtoms::Hello World: Random Seed = 49876732
libAtoms::Hello World: global verbosity = 0

Calls to system_timer will do nothing by default

param_read_line: unknown key /Users/bernstei/Library/Python/3.8/bin/gap_fit
gap_fit
SYSTEM ABORT: Exit: Mandatory argument(s) missing...   
```

**Comment by gabor1** [comment]
--help ?

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by bernstei** [comment]
Same with `--help`.

**Comment by gabor1** [comment]
interesting. the mandatory arg missing and the exit is normal, but the --help is not getting passed to the gap_fit command for some reason. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by bernstei** [comment]
This `sp.call([command] + sys.argv)` from `quippy/cli.py` just looks wrong.  `sys.argv[0]` is already the command name.  Maybe `+ sys.argv[1:]` ?

**Comment by jameskermode** [comment]
Somehow I was not getting notifications about this, sorry. I’ll take a look.

**Comment by jameskermode** [comment]
I only did a minimal test that it invoked the executable, I’m sure you’re right that it’s not passing along the rest of the arguments.

**Comment by jameskermode** [comment]
Should be fixed in the new release candidate here: https://github.com/libAtoms/quippy-wheels/releases/tag/v0.9.4-rc1

Those wheels can be installed with `pip`, but you need to choose the correct version, e.g. for Python 3.9 on an Intel-based Mac

```
pip3 install https://github.com/libAtoms/quippy-wheels/releases/download/v0.9.4-rc1/quippy_ase-0.9.4rc1-cp39-cp39-macosx_10_10_x86_64.whl
```

If this works OK then I'll go ahead with the release to PyPI proper.

**Comment by jameskermode** [comment]
@bernstei I guess this is fixed and can be closed now?

**Comment by stenczelt** [comment]
they do work on my Intel mac now, I agree that we can close this
