### ISSUE TITLE
Provide library for LAMMPS quip pair_style

### ISSUE THREAD

**Issue by jameskermode** [libAtoms/quippy-wheels#2]
Possible ways to do this:
- link existing `_quippy.so` with LAMMPS instead of `libquip.a`
- add `libquip.a` to the Python wheels

**Comment by jameskermode** [comment]
done!

**Comment by dft-dutoit** [comment]
Hi James, 

Apologies for asking perhaps a silly question. How should we go about linking the quippy-ase install to LAMMPS when compiling with either make or cmake?

Thanks

**Comment by jameskermode** [comment]
You should find a libquip.a suitable for linking to LAMMPS inside your quippy installation: you can find where this is with the `quip-config` command line tool provided.

**Comment by dft-dutoit** [comment]
Hi yes, I have found the libquip.a which is located in the site-packages/quippy. But when I run the quip-config tool from within the virtual environment, I get no readout. However, if I run `whereis quip` then I get the location of quip within the environment bin. 

What response should I get from `quip-config`? and would this provide the QUIP_ARCH or QUIP_ROOT responses that should be entered into the Makefile.lammps?

Sorry for the trouble.

**Comment by jameskermode** [comment]
Try `quip-config  --help`. From memory I think you need to supply an ldflags argument.

**Comment by dft-dutoit** [comment]
Ah okay, thanks for all the help. Where would I supply the ldflags argument? And is there any further editing to the Makefile.lammps in the lammps/lib/quip directory required?

**Comment by jameskermode** [comment]
I was wrong, it's `--libs`, e.g on my Mac I get:

```bash
$ quip-config --libs
-L/opt/homebrew/lib/python3.9/site-packages/quippy -lquip
```

These are the linker arguments you need to supply to LAMMPS for it to be able to link to QUIP. I'm not sufficiently familiar with the LAMMPS Makefile system to be able to tell you exactly where to put this.

**Comment by dft-dutoit** [comment]
Brilliant, thanks James I'll go and mess about with that and see what I get. I'll post back here if/when I figure out the installation steps so that others can use it too!
