### ISSUE TITLE
OpenBLAS Warning

### ISSUE THREAD

**Issue by VladCarare** [libAtoms/quippy-wheels#4]
When doing the following, using Quippy (installed via pip install quippy-ase), and ASE 3.21.2b1:
```
from quippy.potential import Potential
from ase.io import read 
atoms_gap = read('S8Ring.cif') # an 8-membered sulphur ring
atoms_gap.calc = Potential(param_filename='GAP.xml') # a potential I trained previously
atoms_gap.get_potential_energy()
```
I get this warning:
> OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.

Although, so far I did not find any consequences of ignoring it. 

Warm regards,
Vlad

**Comment by jameskermode** [comment]
You can safely ignore this warning, but it would be nice to get to the bottom of it at some point

**Comment by albapa** [comment]
is it some internal detection of openmp loop inside another?

**Comment by jameskermode** [comment]
Yes, I guess it's QUIP and OpenBLAS's loops colliding. Don't know why it hasn't shown up before. Maybe it would be better to disable OpenMP for BLAS, but I feel like that would cause a slowdown for linear algebra intensive tasks (like `gap_fit`)

**Comment by jameskermode** [comment]
Closing in preparation for archiving this repo.
