### ISSUE TITLE
Python 3.10

### ISSUE THREAD

**Issue by wcwitt** [libAtoms/quippy-wheels#9]
I was having trouble with
```
$ pip install quippy-ase
ERROR: Could not find a version that satisfies the requirement quippy-ase (from versions: none)
ERROR: No matching distribution found for quippy-ase
```
but I think it's just that I was using python version `3.10`. It works for me with `3.8` and `3.9`.

**Comment by jameskermode** [comment]
Yes, that’s correct. I’ve added 3.10 to the matrix for the next release, but the build is currently broken.

**Comment by jameskermode** [comment]
Now resolved, with wheel building moved to the main [QUIP] (https://github.com/libAtoms/QUIP) repo
